// <auto-generated />
using System;
using Account.WebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Account.WebAPI.Migrations
{
    [DbContext(typeof(AccountMigrationDbContext))]
    [Migration("20220918143259_Ini")]
    partial class Ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Account.Models.Entities.Candidato.CandidatoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_registro");

                    b.Property<int>("Legenda")
                        .HasColumnType("INTEGER")
                        .HasColumnName("legenda");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeVice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome_vice");

                    b.HasKey("Id")
                        .HasName("PK_candidato_id");

                    b.ToTable("candidato", (string)null);
                });

            modelBuilder.Entity("Account.Models.Entities.Voto.VotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_voto");

                    b.Property<int?>("IdCandidato")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_candidato");

                    b.HasKey("Id")
                        .HasName("PK_voto_id");

                    b.HasIndex("IdCandidato");

                    b.ToTable("voto", (string)null);
                });

            modelBuilder.Entity("Account.Models.Entities.Voto.VotoEntity", b =>
                {
                    b.HasOne("Account.Models.Entities.Candidato.CandidatoEntity", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("IdCandidato");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("Account.Models.Entities.Candidato.CandidatoEntity", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
